aeye-lab/pymovements

pylintrc
tox.ini

in the team discussion we decided to switch from 85 characters per line to 100 -- this pull request implements this change.

modify line length from 85 to 100

---

.github/ISSUE_TEMPLATE/BUG.md
.github/ISSUE_TEMPLATE/FEATURE.md
.github/ISSUE_TEMPLATE/config.yml

Fixes #13 
- Insert a description of the changes implemented in the pull request.
Please delete options that are not relevant.

Add issue templates.

---

requirements.txt
setup.cfg
src/pymovements/base.py
src/pymovements/plot.py
src/pymovements/transforms.py

Fix most of the pylint errors.

---

src/pymovements/events/__init__.py
src/pymovements/events/base.py
tests/events/test_events_base.py

This PR adds the first event base classes.
This will help in unifying the output of the event detection functions.
Proposed in #16

Add event base classes

---

src/pymovements/events/base.py
tests/events/test_events_base.py

Fixation detection algorithms may output the position of a fixation. Therefore I added this property to Fixation event class.
- Add position property for fixation event class

Add position property to fixation class

---

tox.ini

Fixes # (issue) (see: [issues](https://github.com/aeye-lab/pymovements/issues))
- Insert a description of the changes implemented in the pull request.

fix broken tox / github action

---

.github/workflows/tests.yml
README.md
setup.cfg
tox.ini

Add support for python310 and 311 to github CI.
Fixes #59

add support for python310 and 311

---

LICENSE

add paul, jakob and shuwen to license

Update License to include pp, jc and sd

---

.github/workflows/tests.yml
README.md
setup.cfg

Add macos and windows to github actions testing pipeline
Fixes #57
- add macos-latest and windows-latest to tests.yml

add macos and windows test environments to github actions

---

pylintrc

Haha, this is ugly but otherwise the GazeBase class has too much similar lines to JuDo1000.
I would like to keep this functionality as it's nice to have some checking of this.
We should reevaluate how to handle this the next time it arises.

CI: increase min-similarity-lines

---

src/pymovements/utils/archives.py
src/pymovements/utils/downloads.py
src/pymovements/utils/paths.py

This PR adds functionality for recursive archive extraction.
If an archive includes archives, it is now possible to automatically extract these archives again.
PR #101 is a dependency and must be merged before.

Utils: recursive extract

---

src/pymovements/base.py

This adds `pos2vel()` to the `Experiment` class, similar to the `pix2deg()` method in `Screen`.

Transforms: Add pos2vel() to Experiment

---

docs/source/bibliography.bib
src/pymovements/datasets/__init__.py
src/pymovements/datasets/gazebase.py

This PR adds the GazeBase dataset.
PRs #91 #103 #102 and #105 need to be merged first.
No testing done for the same reasons as for PR #91

Add GazeBase

---

src/pymovements/transforms.py

This adds a new function to `pymovements.transforms`.
With `consecutive()` we can get a list of arrays with consecutive values from an input array.
This is necessary for #4

Transforms: Add consecutive()

---

CONTRIBUTING.md

link was broken, the tag really uses spaces and no dashes

Docs: Fix good first issues link

---

CONTRIBUTING.md
README.md

Use mailing list instead of my personal mail adress.

Docs: Add mailing list

---

src/pymovements/datasets/base.py

This lead to not being able to pass additional arguments to the savitzky_golay method

Datasets: add kwargs to pos2vel()

---

setup.cfg

Package: Get ready for v0.1.1

---

src/pymovements/transforms.py
tests/test_transformations.py

scipy import was wrong and derivative mode was not activated

Trafos: Fix savitzky golay method in pos2vel()

---

.pre-commit-config.yaml
src/pymovements/plot.py

update pre-commit config

---

.pre-commit-config.yaml
docs/source/conf.py
src/pymovements/base.py
src/pymovements/datasets/base.py
src/pymovements/datasets/judo1000.py
src/pymovements/events/ivt.py
src/pymovements/transforms.py
src/pymovements/utils/archives.py
src/pymovements/utils/checks.py
src/pymovements/utils/downloads.py
src/pymovements/utils/paths.py

this affected a number of files, I have consequently added the respective changes

CI: Add double quote string fixer

---

setup.cfg
tox.ini

Data was not collected correctly and thus no coverage reported was created.
This should be fixed now. WorksOnMyMachine™

CI: Fix coverage report

---

.github/workflows/tests.yml
setup.cfg
tox.ini

This should add the codecov-bot as a GitHub app
https://github.com/apps/codecov

CI: Add codecov-bot to GitHub workflows

---

README.md

Okay now we need to get motiviated to get at least more than 90%.

Docs: Add coverage badge to README.md

---

CONTRIBUTING.md
README.md

I renamed the file from LICENSE to LICENSE.txt and forgot to update the URLs...

Docs: Fix URLs to license file.

---

setup.cfg

Patch release for License URL and examples in docstrings

Package: Get ready for v0.2.1

---

setup.cfg
src/pymovements/events/__init__.py
src/pymovements/events/engbert.py
src/pymovements/events/events.py
src/pymovements/events/idt.py
src/pymovements/events/ivt.py
src/pymovements/utils/checks.py
tests/events/test_engbert.py
tests/events/test_idt.py

All event detection methods now have both positions and velocities parameters, independent of their actual usage.
This change also includes adding a new check that can be used across modules.
This change is the prerequisite for two things:
* a more straight-forward implementation in the coming `detect_events()` method in the `Dataset` class
* a greater range of properties to be included in the event dataframe

Events: Implement common event detection interface

---

src/pymovements/datasets/__init__.py
src/pymovements/datasets/dataset.py
src/pymovements/datasets/gazebase.py
src/pymovements/datasets/judo1000.py
src/pymovements/datasets/public_dataset.py

The `Dataset` class is getting bigger and bigger and this way the code will be more readable.

Datasets: Split Dataset and PublicDataset into own modules.

---

docs/source/_static/custom.css
docs/source/_static/icon.svg
docs/source/conf.py
setup.cfg

This is a complete overhaul of the used style for the sphinx documentation.

Docs: Use new styling for sphinx documentation

---

src/pymovements/datasets/dataset.py

This lets the user choose which eye they want to use for event detection.

Datasets: Add option to select eye for event detection

---

src/pymovements/events/events.py

Events: Add Events.schema

---

src/pymovements/datasets/gazebase.py
src/pymovements/datasets/judo1000.py

Some small fixes in the documentation.

Datasets: Fix docstrings for GazeBase and JuDo1000

---

src/pymovements/datasets/dataset.py

Otherwise a confusing polars error will be raised.

Datasets: Raise RuntimeError if no files have been found

---

src/pymovements/datasets/dataset.py
tests/datasets/test_dataset.py

Tests for new dataset check methods will follow soon in this PR.

Datasets: Refactor attribute checks into own methods

---

src/pymovements/datasets/dataset.py
tests/datasets/test_dataset.py

This way it is possible to load from or save to an alternative directory than the dataset default one.
You can then for example save dataframes from different preprocessing pipelines into separate directories.

Datasets: Support one-time directories for load and save

---

src/pymovements/datasets/dataset.py
tests/datasets/test_dataset.py

Fixes some of the error messages in Datasets and add a test to raise coverage

Datasets: Fix some error messages

---

src/pymovements/datasets/dataset.py
tests/datasets/test_dataset.py

This increases coverage by a bit

Tests: Call Dataset.detect_events() multiple times

---

src/pymovements/datasets/dataset.py
tests/datasets/test_dataset.py

This now behaves consistently with the gaze dataframe which also has some of the fileinfo columns available (like subject_id)

Dataset: Add subset of fileinfo columns to events dataframe

---

src/pymovements/datasets/dataset.py
tests/datasets/test_dataset.py

There were some methods which didn't work properly with monocular datasets.
Now everything should be fixed.

Dataset: Fully support monocular datasets

---

src/pymovements/base.py
src/pymovements/events/engbert.py
src/pymovements/plot.py
src/pymovements/synthetic/step_function.py
src/pymovements/transforms.py
src/pymovements/utils/downloads.py
tests/datasets/test_dataset.py
tests/utils/test_archives.py

unifying codestyle across files

Codestyle: Unify codestyle across all files

---

src/pymovements/utils/downloads.py

Utils: Fix f-string formatting in utils.downloads

---

src/pymovements/utils/downloads.py
tests/utils/test_downloads.py

we might want to refactor this later to use mocks.

Tests: 100% test coverage in utils.download

---

src/pymovements/datasets/dataset.py
src/pymovements/events/event_processing.py
src/pymovements/events/event_properties.py
src/pymovements/events/events.py
src/pymovements/exceptions.py
src/pymovements/gaze/gaze_dataframe.py
tests/datasets/dataset_test.py
tests/events/event_dataframe_test.py
tests/events/event_processing_test.py
tests/events/event_properties_test.py

... took longer than expected but I needed a few iteration to get the architecture right.
This adds an `EventProcessor` and `EventGazeProcessor` class together with two new properties: `peak_velocity` and `dispersion`.
`EventProcessor` is to be used with an `EventDataFrame`, `EventGazeProcessor` is to be used with an `EventDataFrame` and a `GazeDataFrame` in tandem.

Events: Add EventProcessor and EventGazeProcessor

---

pyproject.toml
src/pymovements/datasets/dataset.py

The keyword argument was renamed in v0.16

Datasets: Fix polars.from_dicts arguments

---

src/pymovements/datasets/gazebase.py

Datasets: Fix positional column names in GazeBase

---

docs/source/tutorials/local-dataset.ipynb
src/pymovements/dataset/dataset.py
src/pymovements/dataset/dataset_definition.py
src/pymovements/dataset/public_dataset.py
tests/dataset/dataset_test.py
tests/dataset/public_dataset_test.py

With this PR `Dataset` is now also initiliazed by a `DatasetDefinition`.

Dataset: Use DatasetDefinition in init

---

docs/source/tutorials/R-tutorial.md
docs/source/tutorials/detecting-events.ipynb
docs/source/tutorials/event-properties.ipynb
docs/source/tutorials/heatmap.ipynb
docs/source/tutorials/local-dataset.ipynb
docs/source/tutorials/plot-main-sequence.ipynb
docs/source/tutorials/preprocessing-raw-data.ipynb
docs/source/tutorials/public-datasets.ipynb
docs/source/tutorials/pymovements-in-10-minutes.ipynb
docs/source/tutorials/saving-loading-events.ipynb
docs/source/tutorials/saving-loading-preprocessed.ipynb
src/pymovements/__init__.py
src/pymovements/dataset/__init__.py
src/pymovements/dataset/dataset.py
src/pymovements/dataset/dataset_definition.py
src/pymovements/dataset/dataset_paths.py
src/pymovements/dataset/public_dataset.py
src/pymovements/datasets/gazebase.py
src/pymovements/datasets/judo1000.py
src/pymovements/datasets/toy_dataset.py
src/pymovements/utils/paths.py
tests/dataset/dataset_paths_test.py
tests/dataset/dataset_test.py
tests/dataset/public_dataset_test.py
tests/datasets/gazebase_test.py
tests/datasets/judo1000_test.py
tests/datasets/toy_dataset_test.py
tests/utils/paths_test.py

This PR changes the way we specify paths for datasets.
This is done as the passing of the `root` argument was confusing and the behavior between `Dataset` and `PublicDataset` was different. Also, all the dirname arguments which will be seldomly used crowded the `Dataset.__init__()` method.
The PR aims to have the most simple specification for everyday-use.
I have therefore added a `path` argument which specifies the exact path to the dataset.
If the user really wants to fiddle around and customize, a new `DatasetPaths` object can be used.
The `root` argument is completely gone together with all the dirname stuff.
Instead we now have a `path` argument. If we just specify this, this will be the path to the dataset directory, omitting any root directory specification.
```python
dataset = …
```

Dataset: Add DatasetPaths and use it in Dataset

---

src/pymovements/dataset/dataset.py
src/pymovements/dataset/dataset_files.py

This is a real refactor. No public interface and no functionality has changed.
I have moved all the file related logic (saving, loading, scanning dataset files) into a separate file using simple static functions.

Dataset: Refactor logic into dataset_files

---

src/pymovements/dataset/dataset.py
src/pymovements/plotting/heatmap.py
src/pymovements/plotting/traceplot.py
src/pymovements/utils/parsing.py

PEP8: Constants are usually defined on a module level and written in all capital letters with underscores separating words. Examples include MAX_OVERFLOW and TOTAL.

consistent definitions and global variables according to PEP8

---

docs/source/bibliography.bib
src/pymovements/datasets/__init__.py
src/pymovements/datasets/gazebasevr.py
tests/datasets/datasets_test.py
tests/datasets/gazebasevr_test.py

adding the [gazebasevr](https://www.nature.com/articles/s41597-023-02075-5) dataset.

add gazebasevr dataset

---

tests/dataset/dataset_download_test.py
tests/dataset/dataset_paths_test.py
tests/dataset/dataset_test.py
tests/datasets/gazebase_test.py
tests/datasets/gazebasevr_test.py
tests/datasets/judo1000_test.py
tests/datasets/toy_dataset_eyelink_test.py
tests/datasets/toy_dataset_test.py
tests/events/detection/idt_test.py
tests/events/detection/ivt_test.py
tests/events/detection/microsaccades_test.py
tests/gaze/transforms/center_origin_test.py
tests/gaze/transforms/downsample_test.py
tests/gaze/transforms/norm_test.py
tests/gaze/transforms/pix2deg_test.py
tests/gaze/transforms/pos2acc_test.py
tests/gaze/transforms/pos2vel_test.py
tests/gaze/transforms/savitzky_golay_test.py
tests/gaze/transforms_test.py
tests/synthetic/step_function_test.py
tests/utils/checks_test.py
tests/utils/filters_test.py
tests/utils/strings_test.py

test: Unify pytest.mark.parametrize

---

src/pymovements/plotting/traceplot.py

fix(plotting): Use Agg backend only during testing with pytest

---

src/pymovements/gaze/integration.py
tests/gaze/integration_numpy_test.py
tests/gaze/integration_pandas_test.py

This adds the new GazeDataFrame functionality to merge columns into position, velocity, etc, to the integration functions for numpy and pandas

feat(gaze): Add column merge arguments to integration functions

---

src/pymovements/dataset/dataset.py
src/pymovements/dataset/dataset_files.py
src/pymovements/gaze/gaze_dataframe.py
tests/gaze/gaze_dataframe_unnest_test.py
tests/gaze/gaze_init_test.py
tests/plotting/tsplot_test.py

feat: Add suffixes argument to GazeDataFrame.unnest()

---

src/pymovements/gaze/gaze_dataframe.py
tests/gaze/gaze_dataframe_test.py

Adds the possibility to copy a GazeDataFrame.
Will be needed in resolving #480

feat: Add GazeDataFrame.copy()

---

src/pymovements/events/properties.py

docs: Add latex formulas to event property docstrings

---

.github/workflows/tests.yml

Github provides the action upload-artifact
This way we could preview documentation changes online

ci: Upload documentation artifacts for PRs

---

pyproject.toml

chore: Migrate to polars v0.19

---

pyproject.toml

fix matplotlib<3.8 until we fixed typing

---

CONTRIBUTING.md

update CONTRIBUTING.md about possible pandoc installation

---

tests/gaze/io/csv_test.py

Reusing the data from the public DatasetDefinitions should be more robust for future changes.

tests: Reuse dataset definitions in from_csv tests

---

.github/workflows/docs.yml
.github/workflows/pylint.yml
.github/workflows/tests.yml

this improves readability of our github workflow definitions by keeping them in sepearate files

ci: Refactor GitHub workflows

---

.github/workflows/publish.yml
tox.ini

this should make it possible to publish pymovements packages "with one click"

ci: add publish github workflow

---

pyproject.toml
src/pymovements/events/frame.py
tests/unit/events/frame_test.py

A helpful method for working on  #655
In hindsight I'm not so sure anymre if it is useful at all to have it as an EventDataFrame method

feat: add EventDataFrame.add_trial_column()

---

CONTRIBUTING.md

docs: update contributing.md for new tox command

---

pyproject.toml

build: add typing_extensions to be able to install pymovements from source

---

pyproject.toml

temporary solution to get documentation to run, which failed PR #752

fix automated documentation by pinning sphinx to be <7.4

---

src/pymovements/dataset/dataset_download.py
src/pymovements/datasets/gaze_graph.py
src/pymovements/datasets/gazebase.py
src/pymovements/datasets/gazebasevr.py
src/pymovements/datasets/hbn.py
src/pymovements/datasets/judo1000.py
src/pymovements/datasets/potec.py
src/pymovements/datasets/sb_sat.py
src/pymovements/datasets/toy_dataset.py
src/pymovements/datasets/toy_dataset_eyelink.py
tests/unit/dataset/dataset_download_test.py

rename resource gaze_resource

---

src/pymovements/events/processing.py

Avoid joining gaze and event frames to avoid OOM when calculating event properties.
Fixes #753
This is not a functional change, only memory usage is affected, so I didn't add any new tests.

fix: Avoid event-gaze join to improve memory efficiency when calculating event properties

---

src/pymovements/plotting/main_sequence_plot.py
src/pymovements/plotting/traceplot.py

fixes matplotlib typing which was commented in the deleted lines

fix part of matplotlib lines are type ignored

---

.pre-commit-config.yaml
src/pymovements/dataset/dataset.py
src/pymovements/gaze/gaze_dataframe.py

lint for double indented definitions.

Linter: double indent checker

---

.pre-commit-config.yaml
src/pymovements/datasets/gaze_graph.py

stacked PR for updating `pydoclint` to `0.5.8`
following issue:
- fixes #744 
PRs involved:
- #820
- #821
- #822
- #823
- #824 
- #825 
- #826
- #827
- #828
- #829
- #830 
- #831
- #832
- #833
- #834
- #835
- #836
- #837
- #838

ci: update pydoclint in pre-commit config

---

src/pymovements/utils/checks.py

hotfix: adjust docstring checks are not none

---

docs/source/bibliography.bib
src/pymovements/datasets/__init__.py
src/pymovements/datasets/interead.py
tests/unit/datasets/datasets_test.py

add [InteRead](https://aclanthology.org/2024.lrec-main.802/) dataset

dataset: add InteRead dataset

---

.github/workflows/tests.yml
pyproject.toml
tox.ini

build: add support for python 3.13

---

src/pymovements/datasets/fakenews.py

Co-authored by @aarbeikop (#894)

hotfix: download link fakenewsperception dataset

---

pyproject.toml
src/pymovements/gaze/transforms_numpy.py

first step towards mypy working again for python 3.13. 
ignore override for now

Fix typing 313

---

README.md

since we moved all communication to discord, I added an invitation link to the readme.

add discord to readme

---

docs/source/bibliography.bib
src/pymovements/datasets/__init__.py
src/pymovements/datasets/bsc2.py
tests/unit/datasets/datasets_test.py

I named the file `bsc2` instead of `bscii` because it makes the connection to the "original" BSC dataset slightly more obvious. 
resolves #951

dataset: add BSCII

---

docs/source/bibliography.bib
src/pymovements/datasets/__init__.py
src/pymovements/datasets/provo.py
tests/unit/datasets/datasets_test.py

dataset: add Provo corpus

---

src/pymovements/dataset/dataset_download.py
tests/unit/dataset/dataset_download_test.py

`gaze_resources` is an artifcat from a previous implementation.

docs: improve datasets error message

---

README.md

See https://github.com/aeye-lab/pymovements/pull/977#issuecomment-2688008032

docs: Add subscription link for mailing list

---

docs/source/tutorials/local-dataset.ipynb

Fixes #
- Fix a typo in the tutorial

docs: Fix typo in local-dataset.ipynb

---

src/pymovements/dataset/dataset_library.py
tests/unit/dataset/dataset_library_test.py

Adds `DatasetLibrary.names()` which lists all names of added datasets.

feat: add DatasetLibrary.names()

---

src/pymovements/gaze/gaze_dataframe.py

When working on #1004 pylint advised me to reduce the number of branches in the init method (it exceeded 30 which is quite complex). It's probably a good idea to separate the refactoring into this PR to make reviewing simpler.
This PR reduces branches and complexity by refactoring some of the logic into dedicated private methods.
This is a pure refactoring PR that makes sure that all existing tests pass without adjustements. No tests added.

chore: refactor GazeDataFrame init

---

src/pymovements/gaze/io.py

chore: remove unnecessary ignore of cyclic-import

---

.github/PULL_REQUEST_TEMPLATE.md

PRs often have related issues that they don't resolve completely, or require or are required by other PRs.
This PR adds a context section to the PR template and does some minor changes to the remaining template

chore: add context section to PR template

---

.github/PULL_REQUEST_TEMPLATE.md

The checklist heading had a bullet point, which also made the text below it look weird.

fix: Remove bullet point from PR template

---

tests/unit/gaze/detect_test.py

test: correct time and velocity in detect_test

---

src/pymovements/dataset/_utils/_downloads.py

fix: revert deletion of opener

---

src/pymovements/dataset/dataset_definition.py

#1108 has implemented `Experiment.from_dict()` which can now be reused in `DatasetDefinition.from_yaml()`.

chore: reuse `Experiment.from_dict()` in `DatasetDefinition.from_yaml()`

---

src/pymovements/datasets/onestop.py
src/pymovements/datasets/onestop.yaml

Remove irrelevant items:
- Bug fix
- Documentation update
Resolves #
- #
- #
- #

dataset: OneStop

---

src/pymovements/plotting/heatmap.py

fix: invert y-axis when origin changed

---

docs/source/reference/plotting.rst

docs: add scanpathplot to online documentation

---

docs/source/getting-started.rst

docs: update dev dependency in getting started installation guide

---

.github/CODEOWNERS

Welcome to the team @cbueth :tada:

ci: update CODEOWNERS
