aeye-lab/pymovements

tests/events/test_events_base.py

I removed type hints from one test file to match the rest of the tests -- generally I think we do not need to type tests because we're checking type hints with type checkers and tests are for functionality. functionallity should fail given the wrong type.
- Insert a description of the changes implemented in the pull request.

remove type from tests/events/test_events_base.py to conform with rest of test suite

---

docs/source/reference/index.rst
src/pymovements/synthetic/__init__.py
src/pymovements/synthetic/step_function.py
tests/synthetic/test_step_function.py

Add synthetic.step_function

---

src/pymovements/synthetic/step_function.py
tests/synthetic/test_step_function.py

This adds multi channel support for synthetic.step_function
Fixes issue #80 
Documentation updates will be added soon.

Add multi-channel support for synthetic.step_function

---

src/pymovements/utils/paths.py

While working on the new datasets feature I discovered a bug in `get_filepaths()`:
The explicitly passed regex wasn't passed to the recursive call, so basically all files were listed.
This is really a good case that we should add much more tests to the utils functions.
I'm not sure how to test such functionality correctly, maybe creating some arbitrary folder structure?
Unfortunately I don't have much time for creating tests for this, but I will create an issue later.
So no additional tests unfortunately, due to the tight schedule for the warsaw meeting :(
I'm feeling bad already. 🥺

Utils: fix bug in get_filepaths()

---

README.md

Documentation link was leading to the whole project where the user would have to click on the correct version etc.
Now we automatically lead to the version of the last stable version and have a much more memorizable URL.

Docs: change documentation URL

---

pylintrc

overgeneral-exceptions must specify parent-module.

CI: fix pylint deprecation warning

---

.github/workflows/tests.yml
tox.ini

mypy was missing from checks so now I added these.
I also removed macos and windows from the flake8, pylint, and mypy checking, as these are platform independent and therefore redundant.

CI: add mypy to checks and run checks only on linux

---

tox.ini

This way it is possible to simply run `pytest` and it will include the doctests too.
I will add some in-detail description on this to the CONTRIBUTION.md, as developers don't need to run tests for all python environments during development process.

CI: Add src to pytest testpaths for running doctests

---

tests/test_transformations.py

Merged the single tests for `transforms.pos2vel` and `transforms.deg2vel` into one test by pytest parametrization:
- `test_pix2deg_raise_error` function for `pix2deg` raising error `expected_error` with input `kwargs`
- `test_pos2vel_raise_error` function for `pos2vel` raising error `expected_error` with input `kwargs`
- `test_pix2deg_equals` to check if `pix2deg` returns `expected_value` with input `kwargs` 
- `test_pos2vel_returns` to check if `pos2vel` returns `expected_value` with input `kwargs` and calculation method `method`

Parametrize tests for transformation functions

---

README.md

The <p> tag isn't needed anymore as the <picture> tag already does the centering

Docs: Remove <p> from README.md

---

src/pymovements/utils/paths.py

Currently only one single extension type can be passed to `get_filepaths()`.
This PR adds support for checking for multiple extension types.

Utils: Add support for list of extension in get_filepaths()

---

src/pymovements/base.py
src/pymovements/transforms.py
tests/test_transformations.py

This PR changes some functionality from `pix2deg()`.
Before, `center_origin` was used to center pixel coordinates from the lower left to the center.
Now we have an `origin` argument to specify the location of the origin.
The meaning of the argument is much more understandable this way.
This way we will also be more flexible in the future.
Currently we still only support two cases:
- `center` which is the same as `center_origin=False` 
- `lower left` which is the same as `center_origin=True`

Transforms: refactor center_origin to origin in pix2deg()

---

tests/events/test_events_base.py
tests/synthetic/test_step_function.py
tests/test_transformations.py
tox.ini

Some of the cases are just not necessary for tests. This disables:
- missing-class-docstring
- missing-function-docstring
- protected-access

CI: Disable three pylint checks for tests directory.

---

src/pymovements/datasets/base.py

`read_gaze_files()` checked wrong attribute and
thus would always raise an `AttributeError`.

Datasets: fix critical error in read_gaze_files()

---

.pre-commit-config.yaml

specifying flake8 args is not necessary here, as flake automatically parses tox.ini if present

CI: remove flake8 args from pre-commit

---

mypy.ini
pyproject.toml

Currently our root directory is a bit cluttered with configuration files.
I made a start in resolving this issue by moving the few definitions in the `mypy.ini` to the `pyproject.toml`.
The definitions from `setup.cfg`, `tox.ini` and `pylintrc` will be migrated in some future sprints.
pre-commit and readthedocs unfortunately are stubborn and not willing to support `pyproject.toml`.

CI: Move mypy definitions to pyproject.toml

---

.gitignore

We generate an additional coverage file to be uploaded to codecov on every workflow run. Ignore it for commits.

Git: Ignore coverage.xml

---

README.md

PyPi does not support relative urls to images (PyPi doesn't store these resources after all).
Moreover, PyPi does not support the `<center>` tag.
I fixed this manually for the last releases before building the packages, but if I forget it, I have to create a new release as PyPi does not allow for changing published releases.
I still want to support the use case where you are offline and want to go through the readme and see the nice logo.
So now per default the github resource is shown, and if that fails the relative url is chosen. If that fails again pymovements is just written at the top.
I think that's the best compromise there is to support both environments.

Docs: Fix logo url and centering for both pypi and local usage

---

pyproject.toml
tox.ini

This additionally adds the `NORMALIZE_WHITESPACE` option as default for running doctests

CI: Move pytest config to pyproject.toml

---

README.md
src/pymovements/transforms.py
tests/test_transformations.py

Thanks to the examples in #95 from @theDebbister we could find a bug for the padding in `cut_into_subsequences()`.
Fortunately I never used `keep_padded=True`, but I have added the respective tests to prevent regressions.

Transforms: Fix padding bug in cut_into_subsequences

---

src/pymovements/events/engbert.py
src/pymovements/events/idt.py
src/pymovements/events/ivt.py
tests/events/test_engbert.py
tests/events/test_idt.py
tests/events/test_ivt.py

In the version before a list of Event objects was returned, which would be very inefficient to process.
I did this originally because I had to focus on other things at it seemed to be the most trivial way.
Now as I got a bit more experience with polars I changed this and we now have nice polars DataFrames as an output.
What I'm not sure about, should we now just delete these Event classes?
Fixes issue #65
I have tested this by using the step function.

Events: Return dataframe in detection methods.

---

src/pymovements/__init__.py
src/pymovements/events/__init__.py
src/pymovements/utils/__init__.py

Add top level imports to all init files.
This way using the package is much more comfortable.
Before this raised an error:
```
import pymovements as pm
pm.events.ivt()
Traceback (most recent call last):
File "pymovements/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-3-e589eee00459>", line 1, in <module>
pm.events.ivt()
AttributeError: module 'pymovements' has no attribute 'events'
```
Now it works as expected.
`pymovements.datasets` was already in correct shape.
It's not needed yet for `pymovements.plots` and `pymovements.transforms` as these are single files.

Modules: Provide top-level imports via init files

---

src/pymovements/datasets/__init__.py
src/pymovements/datasets/dataset.py
src/pymovements/datasets/gazebase.py
src/pymovements/datasets/judo1000.py
src/pymovements/datasets/public_dataset.py

This adds a beginner example to GazeBase and JuDo1000.
Both `download` and `extract` are set to false, so no data will be downloaded.
The call to the `load()` method is marked to be skipped for testing.

Datasets: Add examples to GazeBase and JuDo1000

---

.pre-commit-config.yaml

Inserting the license with # commentaries will break the CSS syntax so for simplicity we won't put the license into the css stylesheets

CI: Ignore CSS files for insert-license pre-commit hook

---

docs/source/index.rst

This removes some needless stuff from the index which was inherited from the old styling:
* a table of contents, which is basically useless as it just links to the getting-started, tutorials, api and bibliography. this is already handed in the navigation bar at the top
* some links to indices and module pages, which lead to a very crowded and confusing page which is not very useful IMO
* Second Citing header (without any citing information, duh)
This way we get a much nicer landing page for the documentation.

Docs: Remove table of contents from old style sphinx doc

---

docs/source/_templates/module.rst

This was just a stupid indentation error.
I am still quite a noob when it comes to the rest-syntax

Docs: Fix missing submodules in sphinx documentation

---

src/pymovements/transforms.py
tests/test_transforms.py

Fixes issue #144 
We now take use of the numpy function  [`np.split()`](https://numpy.org/doc/stable/reference/generated/numpy.split.html)
Moreover, I really despise the current name of the function as its very long and verbose.
I propose to rename the function just simply to `split()`.

Transforms: Refactor cut_into_subsequences to split

---

src/pymovements/events/engbert.py
src/pymovements/events/events.py
src/pymovements/events/idt.py
src/pymovements/events/ivt.py
tests/events/test_engbert.py
tests/events/test_idt.py
tests/events/test_ivt.py

All event detection methods raised an index error on generating the event dataframe when there were no events detected.
For each event detection method:

Events: Fix error on empty event list

---

src/pymovements/synthetic/step_function.py
tests/synthetic/test_step_function.py

This adds gaussian noise to the synthetic.step_function()

Synthetic: Add noise to step_function()

---

src/pymovements/datasets/dataset.py
tests/datasets/test_dataset.py

This adds the possibility to manually clear the event dataframe.
Additionally, a `clear` flag is added to the `detect_events()` method to clear the dataframe instead of merging new detections.
Only the `clear()` method has been tested. Testing `detect_events()` is a separate part on my agenda.

Events: Add method to clear event dataframes

---

README.md

The link when clicking on the codecov badge isn't working. I replaced it.
I checked by editing the link and clicking on the badge.

Fix codecov link not working

---

.pre-commit-config.yaml

This will automatically strip evaluated cells from notebooks and also do some style checking.

CI: Add pre-commit hooks for jupyter notebooks

---

.github/workflows/tests.yml

Pandoc is needed for integrating jupyter notebooks into the sphinx documentation.

CI: Install pandoc for docs job

---

pyproject.toml

binder uses python 3.7 by default and somehow sphinx 6.0.0 is only available for py38+.
Which  is strange actually as this should have been detected by CI?
Anyway, this does not work (master):
https://mybinder.org/v2/gh/aeye-lab/pymovements/HEAD
and this works (this branch):
https://mybinder.org/v2/gh/aeye-lab/pymovements/hotfix/sphinx-version

Package: Downgrade sphinx for python3.7 support

---

.github/workflows/tests.yml
pyproject.toml

CI for our documentation is now running on python 3.7 instead of 3.9.
This is related to the PR #208
This was probably the first time the pymovements docs were build on py37 and it instantly failed

CI: Run tox doc builds with python 3.7

---

docs/source/conf.py

I'm totally clueless how this bug was introduced.
By setting the `html_static_path` further up, there shouldn't be a need for using absolute paths at all..
This is just a quick fix and I will look at some point in the future how to use relative paths here again.

Docs: Fix missing logo bug in sphinx

---

src/pymovements/datasets/public_dataset.py

`PublicDataset.extract()` correctly expects files to be in download directory but they are currently downloaded into the root directory.

Datasets: Download resources to download path

---

src/pymovements/transforms.py
tests/test_transforms.py

I added the missing test cases for transforms.py. In addition, I included how to handle one more case in norm(), see below under new functionality.
Fixes issue #180 
I wrote the test as specified here:
New functionality:

Tests: 100% coverage for transforms.py

---

tests/utils/test_paths.py

in this pr we get 100% test coverage for pymovements.utils.paths, resolves #178

Tests: add test coverage for pymovements.utils.paths

---

tests/events/test_engbert.py

basically a hotfix. add a test for the last code transition that was missing from 100% test coverage.

Tests: add 100% coverage for pymovements.events.engbert

---

LICENSE.txt

The `insert-license` pre-commit hook gets confused by the year range in the license file.
Previously this lead to the year `2023-2023` for new files.
Now files that are created this year will get `2023` in the license header.
Files created last year but modified this year will get `2022-2023` in the license header.

License: Update year

---

tests/utils/test_checks.py

while writing tests for `pymovements.utils.paths` I've realized that we have specific error message. I think we should test those within our test coverage.

Tests: improve test coverage for pymovement.utils.checks to account for error messages

---

src/pymovements/utils/archives.py
tests/utils/test_archives.py

added test coverage for pymovements.utils.archives.
I had to rewrite the source file a bit to make pylint happy :)

Tests: add test coverage for pymovements.utils.archives

---

src/pymovements/datasets/dataset.py
src/pymovements/utils/paths.py
tests/datasets/test_dataset.py
tests/utils/test_paths.py

This function is similar to get_filepaths(),
but returns a list of match groupdicts.
This makes it possible to get rid of an unreachable Exception in Dataset.
Currently no tests written for this.
I will wait for tests to adjust from #178

 Utils: Add paths.match_filepaths()

---

src/pymovements/datasets/dataset.py
tests/datasets/test_dataset.py

Otherwise a duplicate columns error was raised when loading in the event dataframes

Dataset: Omit fileinfo columns while saving event dataframes

---

docs/source/conf.py
src/pymovements/datasets/dataset.py
tests/datasets/test_dataset.py

From now on empty jupyter notebooks will be automatically executed for the sphinx documentation.

Docs: Execute jupyter notebooks for sphinx documentation

---

src/pymovements/utils/paths.py

So this one is a bit weird.
Either we have an unreachable path or mypy complains.
I have removed the unreachable path to get 100% coverage and added an ignore instruction for the particular code line.
mypy doesn't seem to get that the relative anchor cannot be None anymore as we check this already in L116.
It seems to be confused that the condition is in conjunction with `relative`, because it works without (but then the functions doesn't work as expected).

Paths: Get rid of unreachable code in match_filepaths

---

tests/utils/test_archives.py

the testcase is unreachable when extract_archive only is used
this coverage enables us to cover the case if _decompress is used
we advise that this method is not used as a standalone

Tests: add test coverage for pymovements.utils._decompress

---

src/pymovements/utils/downloads.py

tqdm 2.45.0 broke pylint linting (see, [tqdm-github](https://github.com/tqdm/tqdm/blob/0bb91857eca0d4aea08f66cf1c8949abe0cd6b7a/tqdm/auto.py#L27))

hotfix: tqdm 2.45.0 broke pylint linting

---

src/pymovements/events/event_properties.py
tests/events/event_properties_test.py

This closes issue #231
Add new event properties: `disposition()` and `amplitude()`
Followup to PR #262
Commit https://github.com/aeye-lab/pymovements/pull/266/commits/76544595c04de0868aca32d24e5153599d2dca3a is the actual change in this PR. the first two commits are from PR #262

Events: Add disposition and amplitude as event properties

---

.pre-commit-config.yaml
src/pymovements/utils/decorators.py

limited to src and not init files
fixes #280

CI: automatically add `from __future__ import annotations`

---

docs/source/tutorials/R-tutorial.md
docs/source/tutorials/detecting-events.ipynb
docs/source/tutorials/event-properties.ipynb
docs/source/tutorials/heatmap.ipynb
docs/source/tutorials/local-dataset.ipynb
docs/source/tutorials/plot-main-sequence.ipynb
docs/source/tutorials/preprocessing-raw-data.ipynb
docs/source/tutorials/public-datasets.ipynb
docs/source/tutorials/pymovements-in-10-minutes.ipynb
docs/source/tutorials/saving-loading-events.ipynb
docs/source/tutorials/saving-loading-preprocessed.ipynb
src/pymovements/datasets/dataset.py
src/pymovements/datasets/gazebase.py
src/pymovements/datasets/judo1000.py
src/pymovements/datasets/public_dataset.py
src/pymovements/datasets/toy_dataset.py
tests/datasets/public_dataset_test.py

This PR removes the download and extract parameters from the initialization of the `PublicDataset` class.
Instead, the user is expected to call `PublicDataset.download()` explicitly. Extracting is done implicitly in this call.
At first this might seem odd as we might already be comfortable how public datasets are downloaded.
But the way it was implemented was rather bad practice, as a constructor is not supposed to do much more than just initializing your object.
That's why `download` was set to `False` per default in `PublicDataset.__init__()`.
Now we have a much more separated responsibilities in the methods:
`PublicDataset.__init__()` initializes your dataset object without any unexpected downloads.
`PublicDataset.download()` downloads and extracts your dataset.
Using …

Dataset: don't download in init() but implicitly extract in download()

---

tests/plotting/heatmap_test.py
tests/plotting/main_sequence_plot_test.py
tests/plotting/traceplot_test.py
tests/plotting/tsplot_test.py

pytest currently throws a warning on my local machine that over 20 plots are open and not closed.
This is because we create new figures for test cases but newer close them.
tests now don't raise any warnings any more. Apart from that I didn't add any tests.

Tests: Close figures after testing plot functions.

---

pyproject.toml

As some things of the polars api changed from 0.16 to 0.17 (`sep` was deprected in 0.16 and removed in 0.17 in favor of `separator`) we will have to update the minimal polars version.
I should have done this already in PR #315

Package: Update polars version

---

docs/source/tutorials/local-dataset.ipynb
src/pymovements/dataset/dataset_definition.py
src/pymovements/dataset/dataset_files.py
src/pymovements/datasets/gazebase.py
src/pymovements/datasets/judo1000.py
src/pymovements/datasets/toy_dataset.py
src/pymovements/utils/strings.py
tests/dataset/dataset_download_test.py
tests/dataset/dataset_test.py
tests/datasets/datasets_test.py
tests/utils/strings_test.py

I added curly braces format for specifying dataset files.
I minimally changed specified functionality by adding need to specify type of value (by default it's string), I think this change is logical because strings are also default option in `filename_format_dtypes`.
So now instead of:
```
r'(?P<subject_id>\d+)_(?P<session_id>\d+).csv'
```
it can be written as:
```
r'{subject_id:d}_{session_id:d}.csv'
```
All other nuances are specified in function's docstring.
Also, old regex method should still work if needed, this change only adds functionality.
Fixes issue #319
- Implemented function `curly_to_regex(s: str) -> re.Pattern` in utils.strings;
- Added unit tests for `curly_to_regex` function (100% coverage);
- Replaced `DatasetDefinition.filename_regex` with …

Dataset: Use curly braces format instead of pure regex

---

src/pymovements/__init__.py
src/pymovements/dataset/__init__.py
src/pymovements/datasets/__init__.py
src/pymovements/events/__init__.py
src/pymovements/events/detection/__init__.py
src/pymovements/gaze/__init__.py
src/pymovements/plotting/__init__.py
src/pymovements/synthetic/__init__.py
src/pymovements/utils/__init__.py

This PR gets rid of all the `noqa: F401` statements for `flake8` by adding all the imports to the `__all__` variable.
No additional tests are needed for this.

refactor: Remove noqa:F401 and add imports via __all__

---

docs/__init__.py
pyproject.toml
src/pymovements/dataset/dataset.py
src/pymovements/dataset/dataset_definition.py
src/pymovements/events/events.py
src/pymovements/gaze/experiment.py
src/pymovements/gaze/gaze_dataframe.py
src/pymovements/gaze/transforms.py
src/pymovements/plotting/heatmap.py
src/pymovements/utils/checks.py
src/pymovements/utils/decorators.py
src/pymovements/utils/downloads.py
tests/__init__.py

ass discussed in PR #293 we add 
```toml
[tools.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
```
to pyproject.toml. 
all code was adjusted accordingly. in some places I didn't figure out what exactly the type is and had to insert Any -- might change this later

CI: Check types more thoroughly with mypy (#295)

---

tox.ini

Some python versions complain about missing this extra when using a `pyproject.toml`

fix(ci): Add toml extra to coverage installation

---

.pre-commit-config.yaml

This PR changes the default pre-commit messages to the conventional commit specification.
For more details see: https://www.conventionalcommits.org/en/v1.0.0/
I will update the contributing guide soon with this spec too!

ci: Use conventional commits specification for autoupdate messages

---

CONTRIBUTING.md

https://www.conventionalcommits.org/en/v1.0.0/

docs: Define the Conventional Commit specification for commit messages

---

src/pymovements/plotting/traceplot.py

okay, next try...
It's seems to me that it's always the `traceplot()` function that fails.
So now let's try to specify this in the module like it was done in https://github.com/microsoft/azure-pipelines-tasks/issues/16426
If that won't work I will have to review the plot function a bit more.
hopefully fixes #324

fix(plotting): Specify matplotlib backend explictly

---

src/pymovements/events/__init__.py
src/pymovements/events/detection/idt.py
src/pymovements/events/detection/ivt.py
src/pymovements/events/detection/microsaccades.py
src/pymovements/events/events.py
tests/events/detection/idt_test.py
tests/events/detection/ivt_test.py
tests/events/detection/microsaccades_test.py

This makes it possible to specify custom event names for your detected events like this:
```python
dataset.detect_events('idt', name='fixation.idt')
dataset.detect_events('ivt', name='fixation.ivt')
```
fixes #321

feat(events): Add support for custom event names

---

tests/dataset/dataset_test.py

I'm really looking forward for less columns and shorter column names, when we start using tuple positions and velocities all over the place.

test: Consistent positional column naming in dataset_set

---

docs/source/tutorials/pymovements-in-10-minutes.ipynb
pyproject.toml
src/pymovements/dataset/dataset_files.py
tests/dataset/dataset_test.py

This allows range objects to be passed in the `subset` argument in `dataset.load()` 
The polars function `is_in()` works perfectly well with range objects, so I just needed to add this as a valid value type.

feat(dataset): Allow range-objects for subset argument

---

src/pymovements/gaze/gaze_dataframe.py
tests/gaze/gaze_dataframe_init_test.py

This PR implements the merging component columns into a single tuple column.
On initializing a dataframe we can now parse lists of column names for the specific type of channel:
```python
gaze = GazeDataFrame(
data=df,
experiment=experiment,
pixel_columns = ['x_pix', 'y_pix'],
position_columns = ['x_dva', 'y_dva'],
velocity_columns = ['x_vel', 'y_vel'],
acceleration_columns = ['x_acc', 'y_acc'],
)
```
This then results in a dataframe like this:
```
>>> gaze.frame
shape: (3, 4)
┌────────────┬────────────┬────────────┬──────────────┐
│ pixel      ┆ position   ┆ velocity   ┆ acceleration │
│ ---        ┆ ---        ┆ ---        ┆ ---          │
│ list[f64]  ┆ list[f64]  ┆ list[f64]  ┆ list[f64]    │
╞════════════╪════════════╪════════════╪══════════════╡
│ [0.1, 0.2] ┆ [1.1, 1.2] ┆ [3.1, …
```

feat(gaze): Add merging component columns into tuple columns

---

src/pymovements/gaze/gaze_dataframe.py
tests/gaze/gaze_dataframe_explode_test.py

This adds very rudimentary functionality to explode a list column into columns for each component.

feat(gaze): Add explode() method to GazeDataFrame

---

docs/source/tutorials/plot-main-sequence.ipynb
src/pymovements/plotting/main_sequence_plot.py
tests/plotting/main_sequence_plot_test.py

feat: Add styling arguments to main sequence plot

---

src/pymovements/gaze/gaze_dataframe.py
tests/gaze/gaze_init_test.py

This allows for more comfortable usage when initializing loaded dataframes.
needed for #479

feat: Allow for empty lists in gaze component initializers

---

src/pymovements/dataset/dataset_files.py
src/pymovements/gaze/gaze_dataframe.py
tests/dataset/dataset_test.py

Closes #480 
The gaze dataframe will now be completely copied before post-processing and saving.

fix: Get rid of unnest side effect during GazeDataFrame.save()

---

src/pymovements/gaze/gaze_dataframe.py

I noticed the `trial_columns` argument was missing from the docstring of `GazeDataFrame`'s constructor. Added it to clarify the usage and effect of this argument.
- Updated the `GazeDataFrame` constructor docstring to include a explanation for the `trial_columns` parameter.

Update GazeDataFrame Docstring to Include Missing trial_columns Argument

---

src/pymovements/gaze/gaze_dataframe.py
src/pymovements/gaze/integration.py

The `time_column` argument was missing from both `gaze.integration.from_numpy()` and `gaze.integration.from_pandas()`

feat: Add time_column argument to gaze.integration functions

---

src/pymovements/gaze/gaze_dataframe.py
tests/gaze/gaze_dataframe_unnest_test.py
tests/gaze/gaze_init_test.py
tests/gaze/gaze_transform_test.py

This PR implements a more robust way of inferring the number of components in a GazeDataFrame.
Fixes issue #514

fix: Infer correct number of components in gaze init

---

src/pymovements/gaze/gaze_dataframe.py
tests/gaze/gaze_transform_test.py

resolves #499 and additionally covers both `pix2deg` and `pos2acc`

raise helpful error message for transforms

---

.github/dependabot.yml

With this PR dependabot should create weekly PRs for updated packages.
See https://docs.github.com/en/code-security/dependabot for reference.
Let's see if that works.

chore: Integrate dependabot to check for dependency updates

---

.github/dependabot.yml

I made an error when writing the config, the scope should not be included in the commit messages

build: don't include scope in dependabot commits

---

src/pymovements/events/frame.py
tests/events/frame_test.py

Adds simple clone method to EventDataFrame class. Needed in #553

feat: Add EventDataFrame.clone()

---

src/pymovements/__init__.py
src/pymovements/dataset/dataset.py
src/pymovements/dataset/dataset_files.py
src/pymovements/events/detection/_ivt.py
src/pymovements/events/processing.py
src/pymovements/gaze/gaze_dataframe.py
src/pymovements/gaze/integration.py
src/pymovements/plotting/traceplot.py
tests/dataset/dataset_test.py
tests/events/detection/idt_test.py
tests/gaze/detect_test.py
tests/gaze/gaze_init_test.py
tests/gaze/integration_numpy_test.py
tests/gaze/integration_pandas_test.py

This is a major step towards a self-contained Gaze class.
We now do not need a Dataset object anymore to run event detection algorithms.
Depends on #553 and #554

feat: Add GazeDataFrame.detect()

---

.github/workflows/tests.yml
.pre-commit-config.yaml
CONTRIBUTING.md
pylintrc
pyproject.toml
src/pymovements/dataset/dataset_library.py
src/pymovements/gaze/transforms.py
src/pymovements/plotting/traceplot.py
tox.ini

build: drop support for python 3.8

---

.github/workflows/tests.yml
.pre-commit-config.yaml
CONTRIBUTING.md
tox.ini

As proposed in #573 linting is now completely run by using pre-commit
Fixes issue #573

ci: Remove mypy and flake8 from tox and github actions

---

src/pymovements/datasets/toy_dataset_eyelink.py

the schema for the ToyDatasetEyeLink was not specified correctly.
Needed to be merged for #590 to work properly

fix: specify schema for ToyDatasetEyeLink

---

.github/release-drafter.yml
.github/workflows/autolabeler.yml

autolabeler doesn't seem to work
here's some more info:
https://github.com/release-drafter/release-drafter/blob/master/README.md
it seems there needs to be a specific worfklow defined

ci: add github workflow for autolabeler

---

.github/workflows/tests.yml

It seems that python is setup twice without being necessary.
Just setup python once instead of twice.

ci: don't setup python twice in github workflow

---

docs/source/conf.py
pyproject.toml

Running our tests raises several warnings. They were just ignored before, but now we will treat each unexpected warning as an error.
As there are already some warnings raised that need to be worked on, I have created ignore-exceptions for these cases. Getting rid of these ignores can be worked on in separate PRs which then can remove the respective ignore line from the pyproject.toml 
These are the added exceptions
https://github.com/aeye-lab/pymovements/blob/ec11568ff43ba2af64ccbf554ed86024055ea34a/pyproject.toml#L132-L142

ci: treat warnings as errors

---

src/pymovements/dataset/dataset_files.py
tests/functional/dataset_processing_test.py

Fixes #607
Changes:
- Only rename input columns by `column_map` when loading raw data
- Test for loading preprocessed dataset. 
Working with the example files currently present in `tests/files` I had to adjust some attributes of the pupil datasets `DatasetDefinition`.

fix: SchemaFieldNotFoundError When Loading Preprocessed Data

---

tox.ini

Currently, if a PR doesn't achieve full test coverage, all pytest workers will fail. This is not nice, as pytest workers failing should signal errors in tests not in coverage. We already have codecov workers which fail on not meeting 100% coverage.
I have added the codecov checks to the required checks that each PR must pass. This way we still guarantee that PRs won't be merged with incomplete test coverage, but pytest workers also won't get red.

ci: don't fail pytest on incomplete coverage

---

.github/release-drafter.yml

Until we hit v1.0.0 this is probably the best way of semantic versioning

build: raise minor version on breaking changes only

---

docs/source/tutorials/detecting-events.ipynb
pyproject.toml

Recently a failure in our CI popped up with messages like these:
```
/home/runner/work/pymovements/pymovements/docs/source/tutorials/detecting-events.ipynb:163: ERROR: Content block expected for the "raw" directive; none found.
```

docs: workaround ci failure by pinning nbconvert<7.14

---

.pre-commit-config.yaml

some error codes were incompatible with *pydoclint*.
added the following ignores:
- src
- D107: Missing docstring in __init__  (pydoclint does not allow for init docstrings)
- D203: 1 blank line required before class docstring
- D213: Multi-line docstring summary should start at the second line
- D413: Missing blank line after last section
- test
- D107: Missing docstring in __init__  (pydoclint does not allow for init docstrings)

ci: update pydocstyle ignores

---

src/pymovements/dataset/dataset_files.py
src/pymovements/gaze/gaze_dataframe.py
tests/unit/gaze/gaze_dataframe_test.py

We discussed this already in November when I added this function, but I forgot to do this apparently.
I guess nobody started to use this method in the meantime, so I would just rename it without deprecation

feat!: rename GazeDataFrame.copy() to clone()

---

pyproject.toml
src/pymovements/events/frame.py
tests/unit/events/frame_test.py

For trializing the event detection method it is nice to have info on the trial columns available in the EventDataFrame class itself.

feat: add trial_columns to EventDataFrame

---

tox.ini

This way it is easier to run tox for a single dataset like this:
```
tox -e integration -- tests/integration/public_dataset_processing_test.py::test_public_dataset_processing[PoTeC]
```
The command should be added to the CONTRIBUTING.md (#692)

ci: improve tox integration command

---

.github/workflows/tests.yml

we currently have some node.js deprecation warnings in our github workflows
This PR  gets rid of these

ci: update github action versions

---

docs/source/bibliography.bib
src/pymovements/datasets/gaze_graph.py
src/pymovements/datasets/gaze_on_faces.py
src/pymovements/datasets/gazebase.py
src/pymovements/datasets/gazebasevr.py
src/pymovements/datasets/hbn.py
src/pymovements/datasets/judo1000.py
src/pymovements/datasets/potec.py
src/pymovements/datasets/sb_sat.py
src/pymovements/datasets/toy_dataset.py
src/pymovements/datasets/toy_dataset_eyelink.py

The checksum of the PoTeC resource file has changed and thus `tox -e integration` failed.
I have updated the checksum.
@theDebbister can you confirm that the zip file has changed?
I can see a revision at the beginning of the current month here: https://osf.io/tgd9q

fix: update checksum of PoTeC resource file

---

src/pymovements/dataset/dataset_files.py
tests/unit/dataset/dataset_files_test.py

integration test did not pass for `ToyDatasetEyeLink`, I checked why, and the experiment definition was not passed correctly. easy fix. added test.

fix: forward experiment from dataset definition to from_asc

---

.github/workflows/tests.yml

ci: use macos-13 instead of macos-latest for python 3.9

---

src/pymovements/events/properties.py
src/pymovements/plotting/tsplot.py
tests/unit/plotting/tsplot_test.py

pylint draw some attention to some erronuous logic in tsplot in #725 
This makes sure that ylims is really set by handling the `not zero_centered_yaxis` branch

fix: fix ylim in tsplot for non-centered yaxis

---

docs/source/tutorials/detecting-events.ipynb
docs/source/tutorials/event-properties.ipynb
docs/source/tutorials/heatmap.ipynb
docs/source/tutorials/local-dataset.ipynb
docs/source/tutorials/plot-main-sequence.ipynb
docs/source/tutorials/preprocessing-raw-data.ipynb
docs/source/tutorials/pymovements-in-10-minutes.ipynb
docs/source/tutorials/saving-loading-events.ipynb
docs/source/tutorials/saving-loading-preprocessed.ipynb
src/pymovements/events/frame.py
src/pymovements/gaze/gaze_dataframe.py

Added string representations to EventDataFrame and GazeDataFrame
Fixes issue # 448

feat: Add __str__() methods to EventDataFrame and GazeDataFrame

---

src/pymovements/gaze/gaze_dataframe.py
tests/unit/gaze/detect_test.py

If there are multiple trial columns, the `group_filter_expression` in `GazeDataFrame.detect()` is built incorrectly, leading to `polars.exceptions.InvalidOperationError: bitand operation not supported for dtype str`. This is because the `&` operator has precedence over `==`.

fix: operator precedence when building group_filter_expression

---

src/pymovements/datasets/gaze_graph.py
src/pymovements/datasets/hbn.py
src/pymovements/datasets/sb_sat.py
tests/functional/dataset_processing_test.py

Some dataset definitions (like SB-SAT) do not include the subject ID in `trial_columns`, while others (like PoTeC) do. There might be a reason for this that I'm unaware of, but it leads to this bug:
```py
sbsat = pm.Dataset("SBSAT", "sb-sat").download()
sbsat.pix2deg().pos2vel(method="savitzky_golay", window_length=11, degree=3)
sbsat.detect("ivt")
sbsat.detect("microsaccades")
print(sbsat.events)
```
In this example, `detect("ivt")` works just fine, but when running `detect("microsaccades")`, the added saccades will have a subject ID `null` in the event frame:
```
shape: (3_541, 7)
┌────────────┬───────────┬───────────┬──────────┬─────────┬─────────┬──────────┐
│ subject_id ┆ book_name ┆ screen_id ┆ name     ┆ onset   ┆ offset  ┆ duration │
│ ---        ┆ ---       ┆ ---       ┆ --- …
```

fix: add subject ID to dataset trial columns

---

src/pymovements/events/processing.py
tests/unit/events/processing_test.py

Currently, kwargs provided by the user in `dataset.compute_event_properties()` are overridden with default values. This means that user-provided kwargs will be ignored. It is also unnecessary, because the event properties currently implemented in `pm.events.properties` already define their own default values.
Fixes issue #735.

fix: Don't override kwargs in EventGazeProcessor

---

src/pymovements/plotting/traceplot.py

Currently, calling `pm.plotting.traceplot(dataset.gaze[0])` in a notebook (even without providing any color values), raises `ValueError: data mapping points must start with x=0 and end with x=1`, because the default cmap definitions are invalid:
https://github.com/aeye-lab/pymovements/blob/5b195e18571aca39f575867aa7fc6549f15c933d/src/pymovements/plotting/traceplot.py#L63-L67
From the [matplotlib documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.LinearSegmentedColormap.html):
> Each row in the table for a given color is a sequence of x, y0, y1 tuples. In each sequence, x must increase monotonically from 0 to 1.
So to keep alpha constant, it would have to look like this:
```py
'alpha': [
(0.0, 1.0, 1.0),
(1.0, 1.0, 1.0),
],
```
but since alpha is constant at 1.0, it …

fix: default traceplot cmaps

---

.pre-commit-config.yaml

types-all is deprecated and leads to pre-commit.ci failing, see e.g. #771

as per repository types-all is deprecated

---

.pre-commit-config.yaml

the double indent linter unfortunately locally destroyed my tests, I'll try to find a minimal example for this and fix it but until then I want to remove it.

hotfix: double indent linter destroyed my tests

---

tests/unit/datasets/datasets_test.py

to account for `precomputed_events` dataset only, refactor the public dataset tests

refactor public dataset tests into 'gaze' and 'precomputed_events'

---

src/pymovements/datasets/copco.py

since we only run integration tests on releases -- there was an unnoticed bug with loading the `precomputed_events` within the public copco dataset.

hotfix: specify custom_read_kwargs in copco to enable loading precomputed_events

---

src/pymovements/utils/aois.py

previously aoi mapping was only with specific columns, now they are adjusted to the dataframes actual naming.

feat: adjust aoi mapping to aoi dataframe columns

---

src/pymovements/datasets/sb_sat.py
tests/functional/gaze_file_processing_test.py

The definition for the SB-SAT dataset included a column in the `trial_columns` field which does not exist in the data files.

fix: correct trial columns in SB-SAT dataset

---

docs/source/reference/index.rst

Some modules where missing from the html documentation. This PR adds these.

docs: Add missing modules to documentation

---

src/pymovements/gaze/__init__.py

The eye tracker class was missing from the docs

fix: correctly add EyeTracker class to gaze module

---

src/pymovements/stimulus/text.py
tests/unit/stimulus/text_test.py

default eyelink aoi files end in `.ias`, hence I add the file type to `from_file` for text stimulus

feat: add support for .ias files in stimulus.text.from_file()

---

src/pymovements/datasets/copco.py

there was a problem due to multi quotation marks

hotfix: CopCo dataset precomputed events loading

---

.github/release-drafter.yml

this should autolabel dataset related pull requests and put them in a dataset section in the release draft

ci: add dataset section to release drafter

---

.github/workflows/tests.yml

Update dependencies on two GitHub actions
- codecov-action v4 -> v5
- upload-artifact v3 -> v4
> GitHub
>Artifact actions v3 will be closing down by January 30, 2025. You are receiving this email because you have GitHub Actions workflows using v3 of [actions/upload-artifact](https://app.github.media/e/er?s=88570519&lid=6648&elqTrackId=867ac6c9fa524bda9764f13bec8f8014&elq=bd6c906f63be4e008de0c641ac450301&elqaid=4286&elqat=1&elqak=8AF5D94B629B77D0B2E640E5D18BB16F179583EB7B3C6735E8C6767FA68D88AEC44B) or [actions/download-artifact](https://app.github.media/e/er?s=88570519&lid=6647&elqTrackId=bb54934dfd8c4c44b0e64ec2f2ba4824&elq=bd6c906f63be4e008de0c641ac450301&elqaid=4286&elqat=1&elqak=8AF57B355AADDDE608896B61A68B985ADA8483EB7B3C6735E8C6767FA68D88AEC44B). > After this date using v3 of these …

ci: update github actions

---

src/pymovements/utils/parsing.py

asc files with an = sign after DISPLAY_COORDS couldn't be parsed. Origin of said asc file is EyeLinkViewer, where the pdf was converted to asc.
bug causing example line: 
`MSG	1946201 DISPLAY_COORDS = 0 0 1919 1079`
Fixes #
```
-        r'MSG\s+\d+[.]?\d*\s+DISPLAY_COORDS\s+(?P<resolution>.*)',
+        r'MSG\s+\d+[.]?\d*\s+DISPLAY_COORDS\s*=?\s*(?P<resolution>.*)',
```
`MSG	1946201 DISPLAY_COORDS = 0 0 1919 1079`
`MSG	2095865.0 DISPLAY_COORDS 0 0 1279 1023`
- [] I have commented my code, particularly in hard-to-understand areas

feat: Improve regex parsing for DISPLAY_COORDS in asc meta data

---

pyproject.toml

the issue with #935 could happen because dependabot didn't check for minor version updates.
according to semantic versioning, deprecations can be introduced in minor version updates. there are basically two ways how we can treat deprecation warnings in CI:
- treat warnings as errors
- print warnings
We decided to treat warnings as errors some time ago and I still think that it's the most sensible approach, as I rarely read the warnings in CI tests. 
The problem is, that we specified major versions as upper bounds in `pyproject.toml`. dependabot would therefore only try to update the dependencies if a major version update happens. that's why the CI suddenly failed in unrelated new PRs, as a deprecation was introduced to polars.
In this PR I changed the upper bounds of the dependencies to …

ci: use minor versions as upper bound in dependencies

---

src/pymovements/gaze/io.py
src/pymovements/utils/parsing.py
tests/unit/utils/parsing_test.py

RaCCooNS (#961) uses non-ASCII .asc files. This PR should allow specifying the encoding using `custom_read_kwargs` as with .csv files.

Add encoding argument to from_asc()

---

.github/release-drafter.yml

I made an error in #988 
the autolabel uses the label `documentation`, all our issues&prs use this label as well.

ci: use correct documentation label in release drafter

---

src/pymovements/utils/downloads.py

I removed the `aeye-lab` prefix as it's not needed at all.

chore: rename user agent to pymovements

---

.github/ISSUE_TEMPLATE/DATASET.md

This enables providing a URL to contributors for creating issues related to their dataset, that adhere to a specific template.
Also, when you click on "New Issue" you will be able to select "New Dataset" next to "Feature Request" or "Issue Report"
issues are automatically labeled as `dataset`.
The template can probably extended with additional sections, so suggestions are welcome!

chore: Create issue template for adding new datasets

---

src/pymovements/datasets/ucl.py
src/pymovements/datasets/ucl.yaml

The UCL dataset fails the tests in #1049 if `remove_finished=True`.
Reason: resource filename is duplicated, hence archive is already removed before being extracted (again).
This is just a workaround before fixing the underlying issue of handling filename duplicates in resources.
Here's one of the failed jobs: https://github.com/aeye-lab/pymovements/actions/runs/13903514974/job/38903529945?pr=1049

fix: deduplicate resource filenames in UCL dataset

---

tests/unit/gaze/transforms/pos2acc_test.py
tests/unit/gaze/transforms/pos2vel_test.py
tests/unit/gaze/transforms/savitzky_golay_test.py

Some of the xfails for our transforms are passing for a while now. This was probably fixed on the polars side. I removed the xfails accordingly.
Fixes #475

ci: remove xfails for #475 as they pass

---

docs/source/conf.py

This fixes the missing source button in our sphinx docs.
We broke it in #660 when migrating to python3.12 and removing `pkg_resources`.
`importlib.resources` has no `require()` method, but you can get the path to the top-module via `files()`.
The function failed silently and therefore returned `None`, leading to the missing source button.
Fixes #1066

docs: add source button to sphinx docs

---

src/pymovements/datasets/toy_dataset_eyelink.py
src/pymovements/datasets/toy_dataset_eyelink.yaml

the dataset was missing the trial columns. I noticed it in #1004 and updated and tested it there, but probably it's better to have a separate PR for the dataset definition change.
I wouldn't like to rewrite the tests with the old-style explicit argument passing for this PR here.

dataset: add trial_columns to ToyDatasetEyeLink

---

pylintrc
src/pymovements/dataset/dataset_files.py
src/pymovements/gaze/gaze_dataframe.py
src/pymovements/gaze/io.py
tests/unit/gaze/io/csv_test.py

Adds automatic column detection to `from_csv()` as it was already available in `GazeDataFrame()`.
I simplified `dataset_files.py` and just use the `auto_column_detect` argument there.
The auto column detection should probably be improved somewhen (see my tests where I needed to rename the columns beforehand), but that's out of scope for this PR.
I also moved the `auto_column_detect` argument to the last position in `GazeDataFrame()`, as I think this way it is more clear what columns are detected.
The csv tests currently only test the shape of the dataframe.
I improved this to check the schema of the dataframes in #1004 but I wouldn't like to rewrite the tests in this PR (I use passing the definition there).

feat: add auto_column_detect to from_csv()

---

src/pymovements/events/frame.py
src/pymovements/gaze/gaze_dataframe.py
src/pymovements/stimulus/text.py
src/pymovements/utils/aois.py
tests/unit/events/event_aoi_mapping_test.py
tests/unit/stimulus/text_test.py
tests/unit/utils/aois_test.py

`utils.aois` is deprecated. Please use `TextStimulus.get_aoi()` instead.
`utils.aois` will be removed in pymovements v0.26.0
Deprecate `utils.aois` in favor of `TextStimulus.get_aoi()`
The following warnings are printed:
```
DeprecationWarning: Call to deprecated function (or staticmethod) get_aoi(). (Please use TextStimulus.get_aoi() instead. This module will be removed in v0.26.0.) -- Deprecated since version v0.21.1.
```
Related to #999

depr: deprecate `utils.aois` in favor of `TextStimulus.get_aoi()`

---

.github/workflows/datasets.yml

`fail-fast` is `true` by default, which leads to cancelled integration tests if one of the datasets fails. This PR sets `fail-fast` to `false`.

ci: set fail-fast to false in integration tests

---

src/pymovements/dataset/dataset.py
src/pymovements/dataset/dataset_definition.py
src/pymovements/dataset/dataset_download.py
tests/unit/dataset/dataset_definition_test.py

Make `DatasetDefinition.long_name` optional and use `DatasetDefinition.name` in disclaimer in case `DatasetDefinition.long_name` is `None`.
No additional tests written. I should probably write at least two tests.
- New functionality

feat: make `DatasetDefinition.long_name` optional

---

.github/workflows/tests.yml

Cancels workflow runs if a newer commit is available to reduce compute. Cancelling is only applied on pull requests, not on main branch.

ci: reduce CI compute by canceling outdated runs in PRs

---

src/pymovements/dataset/dataset_definition.py
src/pymovements/gaze/experiment.py
src/pymovements/gaze/eyetracker.py
src/pymovements/gaze/screen.py

Allowing the two boolean arguments to be passed as positional arguments is error-prone for switchups and can lead to problems with future enhancements and backwards compatiblity. The arguments should be restricted to keyword only until we have a stable interface.

chore!: restrict boolean arguments in `to_dict()` to keyword-only

---

src/pymovements/dataset/dataset_files.py
tests/unit/dataset/dataset_test.py

#1102 has exposed a bug where loaded gaze files share the same experiment instance. 
- Bug fix
- #1102

fix: don't share experiment instance between loaded files

---

src/pymovements/gaze/transforms.py
tests/unit/gaze/gaze_transform_test.py

The docstring listed `"five_point"` as a valid method in `pos2vel()`, but the only accepted spelling for that method is `"fivepoint"`: https://github.com/aeye-lab/pymovements/blob/f093a0b61083747b80ffdcade378aefe169f726e/src/pymovements/gaze/transforms.py#L595

docs: Change `five_point` to `fivepoint`

---

pyproject.toml

Notebooks in tutorials show warning when importing `pymovements`.
When building the sphinx pages locally I encountered this warning, but noticed it is also produced by production/readthedocs.
This warning is raised in every norebook in the tutorial section, in the `stable` and `latest` docs: https://pymovements.readthedocs.io/en/latest/tutorials/local-dataset.html
Looking it up I have found https://github.com/microsoft/vscode-jupyter/issues/12684, describing that `ipywidgets` are not included in the umbrella `jupyter` package.
- Warning is removed
- `ipywidgets` shows second loading bar in pretty
Remove irrelevant items:
- Bug fix
- Documentation update
Solution is up to discussion.
Relates to …

Docs: Remove `tqdm` warnings from notebooks

---

src/pymovements/datasets/bsc.py
src/pymovements/datasets/bsc2.py

The descriptions of the BCS and BSCII corpora were faulty and possibly copy-pasted from some other corpus (most probably from the toy dataset). Both descriptions identically claimed: "This dataset includes monocular eye tracking data from a single participant in a single session. Eye movements are recorded at a sampling frequency of 1,000 Hz using an EyeLink 1000 eye tracker and precomputed events on aoi level are reported." 
However, the reference papers [[Pan et al., 2022](https://pymovements.readthedocs.io/en/stable/bibliography.html#id2), [Yan et al., 2025](https://pymovements.readthedocs.io/en/stable/bibliography.html#id3)]  and the data itself indicate there are 60 participants and various sampling frequencies.  
No tests were performed but i consulted the publications and Deborah …

docs: corrected and expanded the descriptions for BSC and BSCII

---

CONTRIBUTING.md

This PR updates the installation instructions for development dependencies.
On zsh, the command `pip install -e .[dev]` fails with `zsh: no matches found: .[dev]` because zsh interprets [dev] as a glob pattern. This change updates the docs to use `pip install -e '.[dev,docs]'` which works in both bash and zsh.
A short note is added to explain the quoting.
- Documentation update
Resolves N/A (docs fix, no open issue linked)

docs: quote pip extras so command works in zsh

---

.github/release-drafter.yml

I don't understand why, but the bots are never excluded in the release draft.
I removed the trailing `[bot]` and reverted the `dependabot` exclude, as updating package dependencies is useful information in the changelog.

ci: exclude pre-commit-ci bot in release-drafter

---

.github/release-drafter.yml

ignoring the author `pre-commit-ci` in #1306 seems to work, but the contributors with the `[bot]` suffix are still needed to be ignored.
The current release draft now contains the following bots: `@dependabot, @dependabot[bot], @pre-commit-ci[bot]`
Before merging #1306 it was: `@dependabot, @pre-commit-ci`
After merging this PR it should only contain `@dependabot`

ci: revert removing exclude of bot contributors
